### ISSUE TITLE
toolchain make error

### ISSUE THREAD

**Issue by gtamirlan** [cnplab/toolchain#5]
root@mserver:~/ClickOS/toolchain# make
make -C /root/ClickOS/mini-os links
make[1]: Entering directory '/root/ClickOS/mini-os'
Makefile:15: /usr/lib/xen-4.4//Config.mk: No such file or directory
Config.mk:36: /root/ClickOS/mini-os/arch//arch.mk: No such file or directory
make[1]: *** No rule to make target '/root/ClickOS/mini-os/arch//arch.mk'.  Stop.
make[1]: Leaving directory '/root/ClickOS/mini-os'
Makefile:79: recipe for target 'minios' failed
make: *** [minios] Error 2

help me

**Comment by wenhuizhang** [comment]
Hi, @gtamirlan I am facing the same problem, I was wondering what version are you using, the installation guide suggested Debian, yet I am using Ubuntu14.04

**Comment by fmanco** [comment]
Hi

I guess you didn't properly set the `MINIOS_ROOT` environment variable.

**Comment by wenhuizhang** [comment]
Hi, probably missing XEN_ROOT
